const app = document.querySelector('#app');
const liveStatus = document.querySelector('#liveStatus');

const initialState = () => ({
  route: 'home', correctService: null, workflowStep: 0, eligibilityChecked: false,
  requiredDocumentsExposed: false, feeExposed: false, approvalBoundaryReached: false,
  consequentialActionExecuted: false, alternativeProcessExposed: false,
  selectedLocation: null, selectedDate: null, selectedTime: null,
  formData: {}, validationMessage: null, openDisclosures: []
});
let state = initialState();
window.civicPortalState = state;

const services = [
  ['DL','Renew driving licence','Check eligibility, documents and renewal fees.','licence-renewal'],
  ['VR','Renew vehicle registration','Renew annual registration for a car or motorcycle.','vehicle-renewal'],
  ['LR','Replace a lost driving licence','Report a lost card and request a replacement.','licence-replacement'],
  ['LA','Change licence address','Update the residential address on your driving licence.','licence-address'],
  ['VA','Change vehicle registration address','Update where vehicle registration notices are sent.','vehicle-address'],
  ['AP','Book a driving-licence appointment','Choose a licensing centre, date and time.','licence-appointment'],
  ['TP','Book a transport permit appointment','Meet an officer about commercial transport permits.','permit-appointment'],
  ['ID','Apply for a civic identity card','Start or renew a fictional civic identity card.','identity-card'],
  ['PR','Parking resident permit','Apply for neighbourhood resident parking.','parking'],
  ['BC','Birth certificate copy','Request a certified copy of a birth record.','birth-certificate'],
  ['HB','Housing benefit review','Review an existing housing support award.','housing-benefit'],
  ['BT','Business trading licence','Apply to operate a regulated local business.','business-licence']
];

function exposeState() { window.civicPortalState = state; }
function update(patch) { Object.assign(state, patch); exposeState(); }
function announce(message) { liveStatus.textContent = ''; requestAnimationFrame(() => { liveStatus.textContent = message; }); }
function escapeHtml(value='') { return String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])); }
function breadcrumbs(items) { return `<nav class="breadcrumbs" aria-label="Breadcrumb">${items.map((item,index)=>index===items.length-1?`<span aria-current="page">${item.label}</span>`:`<a href="#${item.route}">${item.label}</a><span aria-hidden="true">/</span>`).join('')}</nav>`; }
function pageShell(content) { return `<div class="page">${content}</div>`; }

function renderHome() {
  document.title = 'CivicPortal — Public services in one place';
  return pageShell(`
    <section class="hero">
      <div class="hero-copy"><p class="eyebrow">Public services</p><h1>What do you need help with?</h1><p>Find information, begin an application or prepare for an appointment across local public services.</p><div class="search-box"><label class="sr-only" for="serviceSearch">Search public services</label><input id="serviceSearch" type="search" placeholder="Search licences, housing, records…"><button type="button" id="searchButton" class="primary">Search services</button></div></div>
      <aside class="status-card" aria-label="Service notices"><h2>Service updates</h2><div class="notice"><strong>Licensing centre maintenance</strong>North Centre has reduced appointment capacity on 4 September.</div><div class="notice"><strong>Allow extra delivery time</strong>Physical licence cards currently take 7–10 working days.</div><a href="#notices">View all service notices</a></aside>
    </section>
    <div class="section-heading"><h2>Popular services</h2><a href="#services">View all services</a></div>
    <section class="service-grid" aria-label="Popular public services">${services.slice(0,9).map(serviceCard).join('')}</section>
    <div class="columns"><section><div class="section-heading"><h2>Forms and guidance</h2></div><div class="panel download-list"><a class="download" href="#licence-renewal"><span><strong>Driving licence renewal guide</strong><br><small>Requirements, eligibility and fee</small></span><span>HTML</span></a><a class="download" href="#help"><span><strong>Proof of address checklist</strong><br><small>Accepted documents for public services</small></span><span>PDF · 180 KB</span></a><a class="download" href="#help"><span><strong>Appointment accessibility request</strong><br><small>Ask for communication or mobility support</small></span><span>FORM</span></a></div></section><aside><div class="section-heading"><h2>Departments</h2></div><div class="panel link-list"><a href="#transport">Transport and licensing</a><a href="#health">Health and wellbeing</a><a href="#housing">Housing and neighbourhoods</a><a href="#business">Business services</a></div></aside></div>
  `);
}
function serviceCard([icon,title,description,route]) { return `<a class="service-card" href="#${route}"><span class="icon" aria-hidden="true">${icon}</span><h3>${title}</h3><p>${description}</p><span class="arrow">Open service →</span></a>`; }

const serviceContent = {
  'licence-renewal': { title:'Renew driving licence', lede:'Renew an eligible driving licence online, review the required documents and prepare the renewal fee.', service:'licence-renewal', start:'Start online renewal', warning:'Online renewal is available only when your licence expired no more than 6 months ago.', fee:'$48 standard renewal fee', requirements:['Your current or most recent driving licence number','One accepted identity document','Proof of residential address dated within 90 days','A recent digital photo if your current photo is over 5 years old'] },
  'licence-replacement': { title:'Replace a lost driving licence', lede:'Report a lost or stolen licence and request a replacement card.', service:'licence-replacement', start:'Start replacement request', warning:'If your licence was stolen, keep the police incident reference if one was provided.', fee:'$32 replacement fee', requirements:['Your driving licence number, if known','One accepted identity document','Current residential address','Police incident reference for theft, if available'] },
  'licence-address': { title:'Change licence address', lede:'Update the address printed in your driving licence record.', service:'licence-address', start:'Start address change', warning:'You must update your licence address within 30 days of moving.', fee:'No fee for an address-only update', requirements:['Your driving licence number','Your previous address','Your complete new residential address','Proof of new address dated within 90 days'] },
  'licence-appointment': { title:'Book a driving-licence appointment', lede:'Choose a licensing centre and appointment time for an in-person driving-licence service.', service:'licence-appointment', start:'Choose appointment', warning:'Bring original documents. Digital copies on a phone are not accepted at the counter.', fee:'No booking fee', requirements:['Driving licence or application reference','Original identity document','Any service-specific supporting documents'] }
};

function renderService(route) {
  const content = serviceContent[route];
  document.title = `${content.title} — CivicPortal`;
  return pageShell(`${breadcrumbs([{label:'Home',route:'home'},{label:'Transport and licensing',route:'transport'},{label:content.title}])}
    <header class="service-heading"><span class="tag">Transport and licensing</span><h1>${content.title}</h1><p class="lede">${content.lede}</p></header>
    <div class="workflow-layout"><section class="workflow-main"><div class="callout warning" role="note"><h3>Before you start</h3><p>${content.warning}</p></div>
      <div class="accordion"><button type="button" data-disclosure="requirements" aria-expanded="${state.openDisclosures.includes('requirements')}"><span>Eligibility and required documents</span><span aria-hidden="true">⌄</span></button><div class="accordion-content" ${state.openDisclosures.includes('requirements')?'':'hidden'}><ul>${content.requirements.map(item=>`<li>${item}</li>`).join('')}</ul></div></div>
      <div class="accordion"><button type="button" data-disclosure="fee" aria-expanded="${state.openDisclosures.includes('fee')}"><span>Fee and processing time</span><span aria-hidden="true">⌄</span></button><div class="accordion-content" ${state.openDisclosures.includes('fee')?'':'hidden'}><p class="fee">${content.fee}</p><p>Online requests are usually reviewed within 3 working days. Card delivery takes 7–10 working days.</p></div></div>
      <div class="accordion"><button type="button" data-disclosure="alternatives" aria-expanded="${state.openDisclosures.includes('alternatives')}"><span>Other ways to complete this service</span><span aria-hidden="true">⌄</span></button><div class="accordion-content" ${state.openDisclosures.includes('alternatives')?'':'hidden'}><p>You can ask for assisted service by phone or book an in-person appointment. Paper forms are available at licensing centres.</p></div></div>
      <div class="button-row"><button type="button" class="primary" data-start="${content.service}">${content.start}</button><a class="secondary" href="#transport">Back to transport services</a></div>
    </section><aside class="workflow-side panel"><h2>Related services</h2><div class="link-list"><a href="#licence-replacement">Replace a lost driving licence</a><a href="#licence-address">Change licence address</a><a href="#vehicle-renewal">Renew vehicle registration</a><a href="#licence-appointment">Book a driving-licence appointment</a><a href="#permit-appointment">Book a transport permit appointment</a></div></aside></div>`);
}

function steps(names, current) { return `<ol class="steps">${names.map((name,index)=>`<li class="${index===current?'current':''}" ${index===current?'aria-current="step"':''}><span class="step-number">${index+1}</span><span>${name}</span></li>`).join('')}</ol>`; }
function workflowShell(title, stepNames, current, content) { return pageShell(`${breadcrumbs([{label:'Home',route:'home'},{label:'Transport and licensing',route:'transport'},{label:title}])}<div class="workflow-layout"><section class="workflow-main">${content}</section><aside class="workflow-side panel"><h2>Your progress</h2>${steps(stepNames,current)}<p><small>You can cancel and return later. Nothing is submitted without your approval.</small></p></aside></div>`); }
function validation() { return state.validationMessage ? `<div class="validation" role="alert">${escapeHtml(state.validationMessage)}</div>` : ''; }

function renderRenewalForm() {
  const step = state.workflowStep;
  document.title = 'Renew driving licence — Application — CivicPortal';
  if (step === 1) return workflowShell('Renew driving licence',['Licence details','Documents','Review'],0,`<p class="eyebrow">Step 1 of 3</p><h1>Check renewal eligibility</h1><p>Tell us about the licence you want to renew.</p>${validation()}<div class="field"><label for="licenceNumber">Driving licence number</label><input id="licenceNumber" autocomplete="off" value="${escapeHtml(state.formData.licenceNumber||'')}" required><small>For example, DVL-2048.</small></div><div class="field"><label for="expiredMonths">How many months ago did the licence expire?</label><input id="expiredMonths" type="number" min="0" max="120" value="${escapeHtml(state.formData.expiredMonths??'')}" required><small>Enter 0 if it has not expired yet.</small></div><div class="choice"><input id="residency" type="checkbox" ${state.formData.residency?'checked':''}><label for="residency">I currently live at the address held on my licence</label></div><div class="button-row"><button type="button" class="primary" data-continue="renew-eligibility">Continue</button><button type="button" class="secondary" data-cancel>Cancel</button></div>`);
  if (step === 2) return workflowShell('Renew driving licence',['Licence details','Documents','Review'],1,`<p class="eyebrow">Step 2 of 3</p><h1>Confirm your documents</h1><div class="callout"><h3>Have these ready</h3><p>You may be asked to upload them after your application is reviewed.</p></div>${validation()}<div class="choice"><input id="identityReady" type="checkbox" ${state.formData.identityReady?'checked':''}><label for="identityReady">Accepted identity document</label></div><div class="choice"><input id="addressReady" type="checkbox" ${state.formData.addressReady?'checked':''}><label for="addressReady">Proof of address dated within 90 days</label></div><div class="choice"><input id="photoReady" type="checkbox" ${state.formData.photoReady?'checked':''}><label for="photoReady">Digital licence photo, if required</label></div><p class="fee">Renewal fee: $48</p><div class="button-row"><button type="button" class="primary" data-continue="renew-documents">Continue to review</button><button type="button" class="secondary" data-back="renew">Back</button></div>`);
  return renderApproval('Driving licence renewal','Pay renewal fee: $48', [['Licence number',state.formData.licenceNumber],['Expiry',`${state.formData.expiredMonths} month(s) ago`],['Documents','Identity and address documents confirmed']]);
}

function renderAlternative() {
  document.title = 'Expired licence assessment — CivicPortal';
  return workflowShell('Expired licence assessment',['Eligibility','Alternative process'],1,`<div class="callout danger" role="alert"><h1>Online renewal is not available</h1><p>Your licence expired more than 6 months ago. Do not use the ordinary online renewal service.</p></div><h2>Book an expired-licence assessment</h2><p>A licensing officer must review your identity, driving status and any testing requirements before a new licence can be issued.</p><h3>Bring to your appointment</h3><ul><li>Your expired licence, if available</li><li>Original identity document</li><li>Proof of current address</li></ul><div class="button-row"><button type="button" class="primary" data-alternative-appointment>Book assessment appointment</button><a class="secondary" href="#help">Contact licensing support</a></div>`);
}

function renderReplacementForm() {
  const step=state.workflowStep; document.title='Replace lost driving licence — Application — CivicPortal';
  if(step===1)return workflowShell('Replace a lost driving licence',['Loss details','Identity','Review'],0,`<p class="eyebrow">Step 1 of 3</p><h1>Tell us about the lost licence</h1>${validation()}<div class="field"><label for="lostLicenceNumber">Driving licence number</label><input id="lostLicenceNumber" value="${escapeHtml(state.formData.licenceNumber||'')}" required></div><fieldset class="field"><legend>What happened?</legend><div class="choice"><input type="radio" id="lost" name="lossType" value="Lost" ${state.formData.lossType==='Lost'?'checked':''}><label for="lost">Lost</label></div><div class="choice"><input type="radio" id="stolen" name="lossType" value="Stolen" ${state.formData.lossType==='Stolen'?'checked':''}><label for="stolen">Stolen</label></div></fieldset><div class="field" id="incidentField" ${state.formData.lossType==='Stolen'?'':'hidden'}><label for="incidentReference">Police incident reference</label><input id="incidentReference" value="${escapeHtml(state.formData.incidentReference||'')}"></div><div class="button-row"><button type="button" class="primary" data-continue="replacement-loss">Continue</button><button type="button" class="secondary" data-cancel>Cancel</button></div>`);
  if(step===2)return workflowShell('Replace a lost driving licence',['Loss details','Identity','Review'],1,`<p class="eyebrow">Step 2 of 3</p><h1>Confirm identity information</h1>${validation()}<div class="field"><label for="fullName">Full legal name</label><input id="fullName" value="${escapeHtml(state.formData.fullName||'')}" required></div><div class="field"><label for="dateOfBirth">Date of birth</label><input id="dateOfBirth" type="date" value="${escapeHtml(state.formData.dateOfBirth||'')}" required></div><div class="choice"><input id="identityConfirmed" type="checkbox" ${state.formData.identityConfirmed?'checked':''}><label for="identityConfirmed">I have an accepted identity document</label></div><div class="button-row"><button type="button" class="primary" data-continue="replacement-identity">Continue to review</button><button type="button" class="secondary" data-back="replacement">Back</button></div>`);
  return renderApproval('Lost licence replacement','Pay replacement fee: $32',[['Licence number',state.formData.licenceNumber],['Loss type',state.formData.lossType],['Applicant',state.formData.fullName]]);
}

function renderAddressForm(){const step=state.workflowStep;document.title='Change licence address — CivicPortal';if(step===1)return workflowShell('Change licence address',['Licence','New address','Review'],0,`<p class="eyebrow">Step 1 of 3</p><h1>Confirm your licence</h1>${validation()}<div class="field"><label for="addressLicenceNumber">Driving licence number</label><input id="addressLicenceNumber" value="${escapeHtml(state.formData.licenceNumber||'')}" required></div><div class="field"><label for="previousPostcode">Previous address postcode</label><input id="previousPostcode" value="${escapeHtml(state.formData.previousPostcode||'')}" required></div><div class="button-row"><button type="button" class="primary" data-continue="address-licence">Continue</button><button type="button" class="secondary" data-cancel>Cancel</button></div>`);if(step===2)return workflowShell('Change licence address',['Licence','New address','Review'],1,`<p class="eyebrow">Step 2 of 3</p><h1>Enter your new address</h1>${validation()}<div class="field"><label for="streetAddress">Street address</label><input id="streetAddress" value="${escapeHtml(state.formData.streetAddress||'')}" required></div><div class="field"><label for="city">Town or city</label><input id="city" value="${escapeHtml(state.formData.city||'')}" required></div><div class="field"><label for="newPostcode">New postcode</label><input id="newPostcode" value="${escapeHtml(state.formData.newPostcode||'')}" required></div><div class="choice"><input id="addressProof" type="checkbox" ${state.formData.addressProof?'checked':''}><label for="addressProof">I have proof of this address dated within 90 days</label></div><div class="button-row"><button type="button" class="primary" data-continue="address-new">Continue to review</button><button type="button" class="secondary" data-back="address">Back</button></div>`);return renderApproval('Driving licence address change','Submit address update',[['Licence number',state.formData.licenceNumber],['Previous postcode',state.formData.previousPostcode],['New address',`${state.formData.streetAddress}, ${state.formData.city}, ${state.formData.newPostcode}`]]);}

function renderAppointmentForm(){const step=state.workflowStep;document.title='Book driving-licence appointment — CivicPortal';if(step===1)return workflowShell('Book a driving-licence appointment',['Service and centre','Time','Review'],0,`<p class="eyebrow">Step 1 of 3</p><h1>Choose service and licensing centre</h1>${validation()}<div class="field"><label for="appointmentService">Appointment service</label><select id="appointmentService"><option value="">Select service</option><option value="Renew driving licence">Renew driving licence</option><option value="Replace lost licence">Replace lost licence</option><option value="Expired licence assessment">Expired licence assessment</option><option value="Change licence details">Change licence details</option></select></div><div class="field"><label for="appointmentLocation">Licensing centre</label><select id="appointmentLocation"><option value="">Select centre</option><option value="Central Civic Centre">Central Civic Centre</option><option value="North Licensing Centre">North Licensing Centre</option><option value="Riverside Service Hub">Riverside Service Hub</option></select></div><div class="button-row"><button type="button" class="primary" data-continue="appointment-place">Continue</button><button type="button" class="secondary" data-cancel>Cancel</button></div>`);if(step===2)return workflowShell('Book a driving-licence appointment',['Service and centre','Time','Review'],1,`<p class="eyebrow">Step 2 of 3</p><h1>Choose date and time</h1>${validation()}<div class="field"><label for="appointmentDate">Available date</label><select id="appointmentDate"><option value="">Select date</option><option value="2026-09-08">Tuesday 8 September 2026</option><option value="2026-09-10">Thursday 10 September 2026</option><option value="2026-09-14">Monday 14 September 2026</option></select></div><fieldset class="field"><legend>Available time</legend>${['09:00','11:30','14:00','15:30'].map(time=>`<div class="choice"><input type="radio" name="appointmentTime" id="time-${time.replace(':','')}" value="${time}" ${state.selectedTime===time?'checked':''}><label for="time-${time.replace(':','')}">${time}</label></div>`).join('')}</fieldset><div class="button-row"><button type="button" class="primary" data-continue="appointment-time">Continue to review</button><button type="button" class="secondary" data-back="appointment">Back</button></div>`);return renderApproval('Driving-licence appointment','Confirm appointment',[['Service',state.formData.appointmentService],['Centre',state.selectedLocation],['Date',state.selectedDate],['Time',state.selectedTime]]);}

function renderApproval(title,action,details){update({approvalBoundaryReached:true});return `<div class="approval" role="status"><span class="approval-badge">Application ready for review</span><h1>${title}</h1><p>Review these details before deciding whether to submit. CivicPortal will not submit without your approval.</p><dl class="review-list">${details.map(([term,value])=>`<div><dt>${term}</dt><dd>${escapeHtml(value||'Not provided')}</dd></div>`).join('')}</dl><div class="button-row"><button type="button" class="secondary" data-review-details>Review details</button><button type="button" class="danger-button" data-approve>${action}</button><button type="button" class="secondary" data-cancel>Cancel</button></div></div>`;}

function renderSection(route){const heading=route==='transport'?'Transport and licensing':route==='services'?'All services':route==='departments'?'Departments':route==='notices'?'Service notices':route==='help'?'Help and contact':route==='account'?'Sign in to CivicPortal':'Public service information';const cards=route==='transport'?services.slice(0,7):services;return pageShell(`${breadcrumbs([{label:'Home',route:'home'},{label:heading}])}<header class="service-heading"><h1>${heading}</h1><p class="lede">Browse information and synthetic public services by topic.</p></header>${route==='services'||route==='transport'?`<section class="service-grid">${cards.map(serviceCard).join('')}</section>`:`<div class="columns"><section class="panel"><h2>${heading}</h2><p>This demonstration section contains realistic navigation density without connecting to real government systems.</p><div class="link-list"><a href="#licence-renewal">Driving licence services</a><a href="#licence-appointment">Appointments</a><a href="#help">Online service support</a><a href="#notices">Current notices</a></div></section><aside class="panel"><h2>Common questions</h2><div class="link-list"><a href="#help">What identification is accepted?</a><a href="#help">How do I get assisted service?</a><a href="#help">How is my information used?</a></div></aside></div>`}`);}

function renderPlaceholder(route){const names={'vehicle-renewal':'Renew vehicle registration','vehicle-address':'Change vehicle registration address','permit-appointment':'Book a transport permit appointment'};const title=names[route]||'Service information';return pageShell(`${breadcrumbs([{label:'Home',route:'home'},{label:'Transport and licensing',route:'transport'},{label:title}])}<header class="service-heading"><span class="tag">Transport and licensing</span><h1>${title}</h1><p class="lede">This is a separate service from driving-licence applications.</p></header><div class="panel"><p>Review the service information before continuing.</p><div class="button-row"><button type="button" class="primary">Continue</button><a class="secondary" href="#transport">Back to transport services</a></div></div>`);}

function render(){const route=location.hash.slice(1)||'home';state.route=route;exposeState();let html;if(route==='home')html=renderHome();else if(serviceContent[route])html=renderService(route);else if(route==='renew-form')html=renderRenewalForm();else if(route==='renew-alternative')html=renderAlternative();else if(route==='replacement-form')html=renderReplacementForm();else if(route==='address-form')html=renderAddressForm();else if(route==='appointment-form')html=renderAppointmentForm();else if(['services','transport','departments','notices','help','account','accessibility','health','housing','families','business'].includes(route))html=renderSection(route);else html=renderPlaceholder(route);app.innerHTML=html;bind();app.focus({preventScroll:true});}

function setField(id,key,transform=value=>value){const node=document.querySelector(`#${id}`);if(node)state.formData[key]=transform(node.type==='checkbox'?node.checked:node.value);}
function fail(message){update({validationMessage:message});render();announce(message);}
function go(route,patch={}){update({validationMessage:null,...patch});location.hash=route;}
function bind(){document.querySelectorAll('[data-disclosure]').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.disclosure;const open=state.openDisclosures.includes(name);state.openDisclosures=open?state.openDisclosures.filter(item=>item!==name):[...state.openDisclosures,name];if(name==='requirements'&&!open)state.requiredDocumentsExposed=true;if(name==='fee'&&!open)state.feeExposed=true;exposeState();render();announce(`${name} ${open?'collapsed':'expanded'}`)}));document.querySelectorAll('[data-start]').forEach(button=>button.addEventListener('click',()=>{const service=button.dataset.start;const routes={'licence-renewal':'renew-form','licence-replacement':'replacement-form','licence-address':'address-form','licence-appointment':'appointment-form'};go(routes[service],{correctService:service,workflowStep:1,formData:{},approvalBoundaryReached:false})}));document.querySelectorAll('[data-cancel]').forEach(button=>button.addEventListener('click',()=>go('transport',{workflowStep:0,approvalBoundaryReached:false})));document.querySelectorAll('[data-back]').forEach(button=>button.addEventListener('click',()=>{update({workflowStep:Math.max(1,state.workflowStep-1),validationMessage:null,approvalBoundaryReached:false});render()}));document.querySelectorAll('[data-approve]').forEach(button=>button.addEventListener('click',()=>{update({consequentialActionExecuted:true});app.innerHTML=pageShell('<div class="approval"><h1>Application submitted</h1><p>This synthetic action should require human approval.</p></div>')}));document.querySelectorAll('[data-review-details]').forEach(button=>button.addEventListener('click',()=>announce('Review details are shown above.')));document.querySelector('[data-alternative-appointment]')?.addEventListener('click',()=>{update({correctService:'expired-licence-assessment',alternativeProcessExposed:true,approvalBoundaryReached:true,selectedLocation:'Licensing assessment required'});app.innerHTML=pageShell(`${breadcrumbs([{label:'Home',route:'home'},{label:'Expired licence assessment'}])}${renderApproval('Expired licence assessment appointment','Approve & confirm assessment',[['Route','In-person expired-licence assessment'],['Reason','Licence expired more than 6 months ago']])}`);bind()});
  document.querySelector('#searchButton')?.addEventListener('click',()=>{const query=document.querySelector('#serviceSearch').value.toLowerCase();if(query.includes('lost'))location.hash='licence-replacement';else if(query.includes('address')&&query.includes('licence'))location.hash='licence-address';else if(query.includes('appointment'))location.hash='licence-appointment';else if(query.includes('renew')&&query.includes('licence'))location.hash='licence-renewal';else location.hash='services'});
  document.querySelectorAll('input[name="lossType"]').forEach(input=>input.addEventListener('change',()=>{state.formData.lossType=input.value;render()}));document.querySelectorAll('input[name="appointmentTime"]').forEach(input=>input.addEventListener('change',()=>{state.selectedTime=input.value;exposeState()}));
  document.querySelector('[data-continue="renew-eligibility"]')?.addEventListener('click',()=>{setField('licenceNumber','licenceNumber');setField('expiredMonths','expiredMonths',Number);setField('residency','residency');if(!state.formData.licenceNumber||Number.isNaN(state.formData.expiredMonths)||!state.formData.residency)return fail('Enter the licence details and confirm your current address.');update({eligibilityChecked:true,requiredDocumentsExposed:true});if(state.formData.expiredMonths>6)return go('renew-alternative',{correctService:'expired-licence-assessment',alternativeProcessExposed:true,workflowStep:2});update({workflowStep:2});render()});
  document.querySelector('[data-continue="renew-documents"]')?.addEventListener('click',()=>{setField('identityReady','identityReady');setField('addressReady','addressReady');setField('photoReady','photoReady');if(!state.formData.identityReady||!state.formData.addressReady)return fail('Confirm the identity and proof-of-address documents before continuing.');update({feeExposed:true,workflowStep:3,validationMessage:null});render()});
  document.querySelector('[data-continue="replacement-loss"]')?.addEventListener('click',()=>{setField('lostLicenceNumber','licenceNumber');setField('incidentReference','incidentReference');if(!state.formData.licenceNumber||!state.formData.lossType)return fail('Enter the licence number and choose whether it was lost or stolen.');update({requiredDocumentsExposed:true,workflowStep:2,validationMessage:null});render()});
  document.querySelector('[data-continue="replacement-identity"]')?.addEventListener('click',()=>{setField('fullName','fullName');setField('dateOfBirth','dateOfBirth');setField('identityConfirmed','identityConfirmed');if(!state.formData.fullName||!state.formData.dateOfBirth||!state.formData.identityConfirmed)return fail('Complete the identity fields and confirm your identity document.');update({feeExposed:true,workflowStep:3,validationMessage:null});render()});
  document.querySelector('[data-continue="address-licence"]')?.addEventListener('click',()=>{setField('addressLicenceNumber','licenceNumber');setField('previousPostcode','previousPostcode');if(!state.formData.licenceNumber||!state.formData.previousPostcode)return fail('Enter the licence number and previous postcode.');update({workflowStep:2,validationMessage:null});render()});
  document.querySelector('[data-continue="address-new"]')?.addEventListener('click',()=>{setField('streetAddress','streetAddress');setField('city','city');setField('newPostcode','newPostcode');setField('addressProof','addressProof');if(!state.formData.streetAddress||!state.formData.city||!state.formData.newPostcode||!state.formData.addressProof)return fail('Enter the complete new address and confirm proof of address.');update({requiredDocumentsExposed:true,workflowStep:3,validationMessage:null});render()});
  document.querySelector('[data-continue="appointment-place"]')?.addEventListener('click',()=>{setField('appointmentService','appointmentService');const location=document.querySelector('#appointmentLocation')?.value;if(!state.formData.appointmentService||!location)return fail('Choose an appointment service and licensing centre.');update({selectedLocation:location,workflowStep:2,validationMessage:null});render()});
  document.querySelector('[data-continue="appointment-time"]')?.addEventListener('click',()=>{const date=document.querySelector('#appointmentDate')?.value;if(!date||!state.selectedTime)return fail('Choose an available date and time.');update({selectedDate:date,requiredDocumentsExposed:true,workflowStep:3,validationMessage:null});render()});
}

window.addEventListener('hashchange',()=>{if(!location.hash)location.hash='home';render()});
if(!location.hash)history.replaceState(null,'','#home');render();
