const fs=require('fs'),path=require('path');const{pathToFileURL}=require('url');const{chromium}=require('playwright');
const script=path.join(__dirname,'..','content.js');async function install(page){await page.evaluate(()=>{globalThis.chrome={runtime:{onMessage:{addListener(){}}}}});await page.addScriptTag({path:script})}const observe=page=>page.evaluate(()=>__GuideModeTest.observe());
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:900}}),dir=path.join(__dirname,'..','..','artifacts',`guidemode-goal-conditioned-${new Date().toISOString().replace(/[:.]/g,'-')}`);fs.mkdirSync(dir,{recursive:true});try{
  await page.goto(pathToFileURL(path.join(__dirname,'..','..','index.html')).href);await install(page);await page.screenshot({path:path.join(dir,'01-idle-no-goal.png'),fullPage:true});
  let observation=await observe(page),men=observation.controls.find(item=>item.value==='Men');await page.evaluate(({ref})=>{__GuideModeTest.setVisualMode(true);__GuideModeTest.applyVisualPlan({elements:[],uncertain_refs:[],guide_state:{goal:"Find a men's blue shirt in size small under $70",status:'guiding',instruction:'Choose Men',target:{ref,name:'Men'},supportingRefs:[]}})},{ref:men.ref});await page.screenshot({path:path.join(dir,'02-first-guided-step.png'),fullPage:true});
  await page.evaluate(()=>document.querySelector('input[value="Men"]')?.labels?.[0]?.click());await page.evaluate(()=>document.querySelector('input[value="Shirts"]')?.labels?.[0]?.click());observation=await observe(page);const small=observation.controls.find(item=>item.value==='S'&&item.group_context==='Size');await page.evaluate(ref=>__GuideModeTest.applyVisualPlan({elements:[],uncertain_refs:[],guide_state:{goal:"Find a men's blue shirt in size small under $70",status:'guiding',instruction:'Choose Small',target:{ref,name:'Small'},supportingRefs:[]}}),small.ref);await page.screenshot({path:path.join(dir,'03-mid-task-small.png'),fullPage:true});
  const civic=await browser.newPage({viewport:{width:1280,height:900}});await civic.goto(pathToFileURL(path.join(__dirname,'..','..','civic-portal','index.html')).href);await install(civic);let civicObs=await observe(civic),route=civicObs.routes.find(item=>/replace a lost driving licence/i.test(item.text));await civic.evaluate(ref=>{__GuideModeTest.setVisualMode(true);__GuideModeTest.applyVisualPlan({elements:[],uncertain_refs:[],guide_state:{goal:'Replace my lost driving licence',status:'guiding',instruction:'Open replacement guidance',target:{ref,name:'Replace a lost driving licence'},supportingRefs:[]}})},route.ref);await civic.screenshot({path:path.join(dir,'04-route-guidance.png'),fullPage:true});
  const evidence=civicObs.content.find(item=>/fee|cost|require/i.test(item.text))||civicObs.content[0];await civic.evaluate(ref=>__GuideModeTest.applyVisualPlan({elements:[],uncertain_refs:[],guide_state:{goal:'What do I need?',status:'completed',instruction:'',target:null,supportingRefs:[ref],explanation:'The page contains the requested information.'}}),evidence.ref);await civic.screenshot({path:path.join(dir,'05-information-evidence.png'),fullPage:true});
  await civic.evaluate(()=>location.hash='#replacement-form');await civic.waitForTimeout(100);civicObs=await observe(civic);const sensitive=civicObs.controls.find(item=>/licence number/i.test(item.name))||civicObs.controls.find(item=>item.role==='textbox');if(sensitive){await civic.evaluate(ref=>__GuideModeTest.applyVisualPlan({elements:[],uncertain_refs:[],guide_state:{goal:'Replace my lost licence',status:'waiting_for_user',instruction:'Enter your driving licence number',target:{ref,name:'Driving licence number'},supportingRefs:[]}}),sensitive.ref)}await civic.screenshot({path:path.join(dir,'06-sensitive-manual-step.png'),fullPage:true});
  await page.evaluate(()=>__GuideModeTest.applyVisualPlan({elements:[],uncertain_refs:[],guide_state:{goal:"Find a men's blue shirt",status:'completed',instruction:'',target:null,supportingRefs:[],explanation:'Matching products are shown.'}}));await page.screenshot({path:path.join(dir,'07-completed-goal.png'),fullPage:true});await page.evaluate(()=>__GuideModeTest.setVisualMode(false));await page.screenshot({path:path.join(dir,'08-show-original.png'),fullPage:true});console.log(`Goal-conditioned screenshots: ${dir}`);await civic.close();
}finally{await page.close();await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
